### ISSUE TITLE
Locations and Rows

### ISSUE THREAD

**Issue by q1x** [rvojcik/rtapi#1]
Hi,

I really like the possibility to interact with the racktables database from Python.
However, I'm currently missing Location, Row and Rack data which are vital for the project I'm working on.

Would it be possible for you to add those?

Hope to hear from you,

Raymond

**Comment by rvojcik** [comment]
Hi, 

it's good idea ! I absolutely forgot about rows/racks and locations in rtapi. I will add this feature this week.

**Comment by rvojcik** [comment]
Not, realy. It was the plan but not started with it
