### ISSUE TITLE
Get Objects with given tag

### ISSUE THREAD

**Issue by laimaretto** [rvojcik/rtapi#11]
Hi!

Today I have some SQL queries that I use on my own to obtain one or all the objetcs that have such a `tag`. Do you think it is feasible to implement it in the library? I can provide those queries if interested...

I've been seraching for the methods and I've found only `rt.GetObjectTags(id)`. This would be the other way around: given a `tag` obtain the list of `object_id`.
 
thanks!

**Comment by rvojcik** [comment]
Hi @laimaretto , 
great idea !

I will definitely implement it.
