### ISSUE TITLE
Typo in InsertOrUpdateAttribute

### ISSUE THREAD

**Issue by astapelfeld** [rvojcik/rtapi#4]
There is type here causing this error:

_mysql_exceptions.ProgrammingError: (1146, "Table 'racktables.object' doesn't exist")

'object' should be capitalized -> 'Object' in the SQL query

```
 def InsertOrUpdateAttribute(self, object_id, attr_id, new_value):
        # Get the object type
        sql = "SELECT objtype_id FROM object WHERE id = %d" % (object_id)
result = self.db_query_one(sql)
```

**Comment by rvojcik** [comment]
Hi @astapelfeld ,
thank you for using rtapi. You are right, good job. 
Thank you much for reporting this.I pushed it to master along with another bug. I will create new release in a minute.

**Comment by astapelfeld** [comment]
Hi,

Line 738

sql = "SELECT type FROM attribute WHERE id = %d" % (attr_id)

attribute should also be capitalized.. Found it after posting the issue yesterday.. should have updated the post :-)

**Comment by rvojcik** [comment]
Perfect :) thank you. 
For now I have covered only 42% of the code with automated tests. Still long way to go.
